### ISSUE TITLE
Update version constraint info

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang#274]
app/views/packages/show.mustache needs to be updated to avoid recommending "any" for application packages.

Also, it could use ^ syntax.

For example, https://pub.dartlang.org/packages/angular2 could use this:

```
dependencies:
  angular2: ^2.0.0-alpha.23

For more information, see the [version constraints](https://www.dartlang.org/tools/pub/dependencies.html#version-constraints) section of [Pub Dependencies](https://www.dartlang.org/tools/pub/dependencies.html).
```

Another problem is that alpha packages generally should NOT use ^... Maybe there could be a convention that if the name contains "alpha", the dependency is exactly the one version?

**Comment by nex3** [comment]
> Another problem is that alpha packages generally should NOT use ^... Maybe there could be a convention that if the name contains "alpha", the dependency is exactly the one version?

There's nothing specific about the name "alpha"; it has the same semantics as any prerelease package. The constraints that should be used for prereleases are a bit weird, because theoretically they can make backwards-incompatible changes at any point... we could also recommend `>=2.0.0-alpha.23 <2.0.0` to be on the safe side.
